# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1cc4f391f847c9b8eeeb9fceacac7aa013557e322603b1e5699347b958bbfac8ee1e257ef2b18f755706ff6d074d4300d9c1a5795e49e24fd0706e9654f7d8a3

test:
  secret_key_base: ca73e69b229a772366fba3a4f4a197aedac91beb20447b6115b6fc910fdc47528df63fa69007523546926d81dff0809a23917751e7e5e7720522b86f60c11219

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
